Minor Updates in Readme.md
Rise-Software/Rise-Media-Player pull request #45
Opened 2021-11-02 15:04 UTC by Jathurshan-2019

Added How to install this file without Trusted Certificate
Fixed some Markdown errors in the original file
Made some elements look better

2021-11-03 08:10 UTC, itsWindows11 commented on readme.md
> +Created with WinUI and the latest design ideologies, Rise Media Player is modern while keeping all of the classic features people need. We use WinUI 2.6/2.7 to keep our user interface, clean, modern
```
with Windows 11 UI
```
Both UI and UX apply to this app, so you could include both.

2021-11-03 08:12 UTC, itsWindows11 commented on readme.md
> +Contribute to this Project by Github in [RMP](https://github.com/Rise-Software/Rise-Media-Player)
```
Contribute to this Project by Github in [RMP](https://github.com/Rise-Software/Rise-Media-Player)
```
You could perhaps change this to the snippet below:

```
[Contribute to this Project](https://github.com/Rise-Software/Rise-Media-Player)
```

2021-11-03 08:13 UTC, itsWindows11 commented on readme.md
> +Created with WinUI and the latest design ideologies, Rise Media Player is modern while keeping all of the classic features people need. We use WinUI 2.6/2.7 to keep our user interface, clean, modern
```
with Windows 11 UI
```
Both UI and UX apply to this app, so you could include both.

2021-11-03 08:14 UTC, itsWindows11 requested changes
Overall, this looks good, but there are changes I have suggested to you, you can read them above this comment.

I don't know how to properly review a pull request so sorry for the messed up review.

2021-11-03 08:19 UTC, itsWindows11 commented on readme.md
> +# Rise Media player
```suggestion
# Rise Media Player
```

2021-11-04 01:43 UTC, Jathurshan-2019 commented
That's ok, it is not a problem for me, I will correct it. Thank you for your correction

2021-11-04 01:45 UTC, Jathurshan-2019 commented on readme.md
> +Created with WinUI and the latest design ideologies, Rise Media Player is modern while keeping all of the classic features people need. We use WinUI 2.6/2.7 to keep our user interface, clean, modern
Ok

2021-11-04 01:52 UTC, Jathurshan-2019 commented
Check whether it is ok or not

2021-11-04 11:21 UTC, itsWindows11 commented
> Check whether it is ok or not

I'll check it out again and get back to you when I'm done

2021-11-04 11:23 UTC, itsWindows11 commented on readme.md
> +* Confirmation windows will appear After that Try Installing the MSIXBUNDLE
```suggestion
* Confirmation windows will appear, after that try installing the MSIXBUNDLE
```

2021-11-04 11:24 UTC, itsWindows11 commented on readme.md
> +* Select Place all certificates in Following store and click browse select Trusted People and click OK and Next
```suggestion
* Select "Place all certificates in following store" and click browse, then select "Trusted People" and click OK and Next
```

2021-11-04 11:27 UTC, itsWindows11 commented on readme.md
> +* Simply right click and Go to Digital signatures Tab
```suggestion
* If Windows prompts about Rise Media Player being an untrusted application, simply right click and go to "Digital signatures" tab
```

2021-11-04 11:28 UTC, itsWindows11 commented on readme.md
> +
You don't need to put the app name three times here.

2021-11-04 11:29 UTC, itsWindows11 requested changes
There are some other things you have to change here, too!

2021-11-04 11:58 UTC, merged